### ISSUE TITLE
event pid and idle pid maybe not the same.

### ISSUE THREAD

**Issue by yihong0618** [jnidzwetzki/pg-lock-tracer#78]
as the image
![image](https://github.com/jnidzwetzki/pg-lock-tracer/assets/15976103/b1c22925-2959-47b5-95dc-464fd97bdc09)

**Comment by jnidzwetzki** [comment]
Hi @yihong0618,

Thanks for opening this issue. I am not sure I can follow entirely here. Could you elaborate a bit on why this change is needed and the PID can change?

**Comment by yihong0618** [comment]
yes I use orb https://orbstack.dev/ caused this issue

maybe like this https://github.com/iovisor/bcc/issues/1329

**Comment by jnidzwetzki** [comment]
Hi @yihong0618,

I think I haven't fully understood the problem so far. Is the problem you are facing that you don't see events because they are running in another backend? Have you verified (e.g., by executing `select * from pg_backend_pid();`) that the backend you are connected is actually included in the filter list?

**Comment by yihong0618** [comment]
sorry for late reply, will try to reproduce it these days
